# Generated by Django 4.2.6 on 2023-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=11)),
                ('issues_date', models.BigIntegerField(verbose_name='Unix time stamp of issued date.')),
                ('valid_till', models.BigIntegerField(verbose_name='Unix time stamp of expiry date.')),
                ('pass_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'issued_pass',
            },
        ),
        migrations.CreateModel(
            name='LunchTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('opening_time', models.CharField(max_length=10)),
                ('closing_time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lunch_timings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=11)),
                ('kmitrollno', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(default='-1', max_length=2)),
                ('dept', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=5)),
                ('picture', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
