# Generated by Django 4.2.6 on 2023-10-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_issued_passes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issuedpass',
            table='Issued_Pass',
        ),
    ]
