# Generated by Django 4.2.6 on 2023-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
