# Generated by Django 4.2.6 on 2023-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_issued_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpass',
            name='issues_date',
            field=models.BigIntegerField(verbose_name='Unix time stamp of issued date.'),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='pass_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issuedpass',
            name='valid_till',
            field=models.BigIntegerField(verbose_name='Unix time stamp of expiry date.'),
        ),
    ]
