# Generated by Django 4.2.6 on 2023-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_alter_issuedpass_issues_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=11)),
                ('kmitrollno', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=5)),
                ('secton', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
