# Generated by Django 4.2.6 on 2023-11-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
