# Generated by Django 4.2.6 on 2023-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='-1', max_length=2),
        ),
    ]
