name: Build
on: 
  push:
    paths: 
      - client/*
      - .github/workflows/build.yml
  workflow_dispatch: 
jobs:
  build:
    runs-on: windows-latest
    

    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        shell: bash
        run: |
          cd client
          python -m venv .venv
          ls .venv/Scripts
          ls .venc/scripts
          . ./.venv/Scripts/activate.sh
          pip install -r ./requirements.txt
          python ./build-exe.py
          ls 
          ls dist

